### ISSUE TITLE
非常漂亮的主题，希望能支持简体中文

### ISSUE THREAD

**Issue by Yuki-Judai** [onemid/typora-aqua#1]
非常漂亮的主题，希望能支持简体中文

**Comment by onemid** [comment]
Hello,
Thanks for your recommendation; we will put this feature in the next release. (Maybe in the next few days.)

Hope you enjoy it!

**Comment by onemid** [comment]
Hi,
We just released the new version and instructions about supporting the full Simplified Chinese characters.

Wish u a nice day!

**Comment by Yuki-Judai** [comment]
Awesome ! I'll try it !
